name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: ✨ Features
    labels: [feat, feature]
  - title: 🐛 Fixes
    labels: [fix, bugfix, bug]
  - title: 📦 Maintenance
    labels: [chore, deps, dependencies, refactor, style]
  - title: 🧪 Tests
    labels: [test, testing]
  - title: 📖 Docs
    labels: [docs, documentation]
  - title: ⚡ CI/CD
    labels: [ci, build]

change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&' # allow markdown formatting

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## 🎉 New in v$RESOLVED_VERSION

  $CHANGES

  ### 🙌 Contributors
  Thanks to everyone who contributed to this release:

  $CONTRIBUTORS

  ### 📦 Installation & Upgrade
  ```bash
  pnpm install payload-plugin-pagespeed@$RESOLVED_VERSION
  ```
