name: PR Lint Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr-lint-title:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate PR title
        id: validate
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          REGEX="^(build|chore|ci|docs|feat|fix|perf|refactor): .{1,50}$"

          if [[ ! "$TITLE" =~ $REGEX ]]; then
            echo "valid=false" >> "$GITHUB_OUTPUT"
          else
            echo "valid=true" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        if: steps.validate.outputs.valid == 'false'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          identifier: pr-title-lint
          body: |
            🚨 PR title does not follow Conventional Commits.
            **Format should be:** `<type>: <short-description>`
            **Allowed types:** build, chore, ci, docs, feat, fix, perf, refactor
            *No scopes are allowed.*
          if-no-comment: create
          edit-mode: replace
      
      - name: Remove comment if title is valid
        if: steps.validate.outputs.valid == 'true'
        uses: peter-evans/delete-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-identifier: pr-title-lint
