name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      id-token: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }} # fine-grained PAT with Contents: write + Metadata: read
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}      # if you publish to npm
        run: npx semantic-release --dry-run
