name: release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode'
        required: false
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      id-token: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile

      - name: Determine next version
        id: next_version
        run: npx semantic-release --dry-run
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: pnpm build

      - name: Bump version files
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: |
          npm version ${{ steps.next_version.outputs.new-release-version }} --no-git-tag-version

      - name: Create Release PR
        id: release_pr
        if: ${{ github.event.inputs.dry_run != 'true' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.RELEASE_PAT }}
          commit-message: "chore: bump release to ${{ steps.next_version.outputs.new-release-git-tag }} [skip ci]"
          branch: release/${{ steps.next_version.outputs.new-release-version }}
          title: "chore: bump release to ${{ steps.next_version.outputs.new-release-git-tag }} [skip ci]"
          body: "This PR bumps the package version to ${{ steps.next_version.outputs.new-release-version }}."
          base: main
          labels: release

      - name: Enable Pull Request Automerge
        run: gh pr merge ${{ steps.release_pr.outputs.pull-request-number }} --merge --auto --squash
        if: ${{ github.event.inputs.dry_run != 'true' }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PAT }}

      - name: Create .npmrc
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        if: ${{ github.event.inputs.dry_run != 'true' }}
