name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04

    permissions:
      contents: write      # required for creating a release
      id-token: write      # required for npm provenance
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Get release version
        id: drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and create tag
        run: |
          VERSION=${{ steps.drafter.outputs.tag_name }}
          pnpm version --no-git-tag-version $VERSION
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json pnpm-lock.yaml
          git commit -m "chore: release bump version to $VERSION"
          # git tag $VERSION
          # git push origin HEAD --tags
          echo $VERSION

      - name: Publish to npm
        run: |
          # pnpm publish --access public
          pnpm publish --dry-run --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
