name: tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    paths-ignore:
      - 'docs/**'
      - '*.md'

  push:
    branches:
      - main

env:
  DO_NOT_TRACK: 1 # Disable Turbopack telemetry
  NEXT_TELEMETRY_DISABLED: 1 # Disable Next telemetry
  DATABASE_URI: mongodb://localhost:27017/payload-plugin-pagespeed
  NODE_ENV: test

jobs:
  tests-int:
    runs-on: ubuntu-24.04

    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
    
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      
      - run: pnpm install --frozen-lockfile

      - name: Run integration tests
        run: pnpm test:int

  tests-e2e:
    runs-on: ubuntu-24.04

    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - run: pnpm i --frozen-lockfile

      - name: Restore Playwright cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium --with-deps

      - name: Build
        run: pnpm build

      - name: Run e2e tests
        run: pnpm test:e2e

  all-green:
    name: All Green
    if: always()
    runs-on: ubuntu-24.04
    needs:
      - tests-int
      - tests-e2e
    
    steps:
      - if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
        run: exit 1
